service: vocabulary-improver

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["VocabularyDynamoDBTable", "Arn" ] }
  environment:
    NAMES_TABLE: { "Ref": "VocabularyDynamoDBTable" }

functions:
  addWord:
    handler: handler.addWord
    events:
      - http:
          path: word
          method: post
          cors: true
  getWord:
    handler: handler.getWord
    events:
      - http:
          path: word
          method: get
          cors: true

resources:
  Resources:
    VocabularyDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: word
            AttributeType: S
        KeySchema:
          -
            AttributeName: word
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
